question = document.getElementById('question')
answer = document.getElementById('answer')

question.innerHTML = "Question 2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

// answer.innerHTML = "Answer is"

function arrSum(arr){
    return arr.reduce((a,b)=>a+b,0)
}

function fib(){
    var series = [1,2]
    var count = 0

    while(true){
        series.push(series[count] + series[count+1])
        count++
        if (Math.max(series)>4000000){
            break
        }
    }

    var even = []
    for (let i = 0; i<length(series);i++){
        even.push(series[i])
    }
    answer.innerHTML = "Answer is "+ arrSum(even)
}

fib()